# Generated by Django 4.2.7 on 2023-11-15 12:55

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='modelform',
            name='date',
        ),
        migrations.RemoveField(
            model_name='modelform',
            name='email',
        ),
        migrations.RemoveField(
            model_name='modelform',
            name='name',
        ),
        migrations.RemoveField(
            model_name='modelform',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='modelform',
            name='text',
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', models.TextField(blank=True)), ('email', models.EmailField(blank=True, max_length=254)), ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RU')), ('date', models.DateField(blank=True, help_text='YYYY-MM-DD or DD.MM.YYYY', null=True))], max_length=5)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_app.formtemplate')),
            ],
        ),
    ]
